BEGIN TRANSACTION;
CREATE TABLE "warranty" (
	`id_warranty`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_text`	TEXT NOT NULL,
	`date`	TEXT NOT NULL
);
CREATE TABLE "type_report" (
	`id_report`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`template`	INTEGER NOT NULL
);
CREATE TABLE "report" (
	`id_report`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_type_report`	INTEGER NOT NULL,
	`id_warranty`	INTEGER NOT NULL
);
CREATE TABLE "processes" (
	`id_process`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_comment`	INTEGER NOT NULL,
	`id_qr_code`	INTEGER NOT NULL,
	`id_user`	INTEGER NOT NULL,
	`id_report`	INTEGER NOT NULL,
	`id_client`	INTEGER NOT NULL
);
INSERT INTO `processes` VALUES (1,0,0,0,0,0);
INSERT INTO `processes` VALUES (2,0,0,0,0,0);
INSERT INTO `processes` VALUES (3,0,0,0,0,0);
INSERT INTO `processes` VALUES (4,0,0,0,0,0);
INSERT INTO `processes` VALUES (5,0,0,0,0,0);
INSERT INTO `processes` VALUES (6,0,0,0,0,0);
CREATE TABLE "jobtitiles" (
	`id_jobtitle`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_role`	INTEGER NOT NULL
);
CREATE TABLE "comment" (
	`id_comment`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`text_comment`	TEXT NOT NULL
);
CREATE TABLE "Users" (
	`id_user`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_jobtitle`	TEXT NOT NULL,
	`fio_user`	TEXT NOT NULL,
	`tel_user`	TEXT NOT NULL
);
INSERT INTO `Users` VALUES (1,'admin','admin','88005553555');
CREATE TABLE "Roles" (
	`id_role`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Possibilities`	INTEGER NOT NULL
);
CREATE TABLE "QR_codes" (
	`id_qr_code`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Text_qr_code`	TEXT NOT NULL,
	`img_link_qr_code`	TEXT NOT NULL
);
CREATE TABLE "Clients" (
	`id_client`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`fio_client`	TEXT NOT NULL,
	`tel_client`	TEXT NOT NULL
);
COMMIT;
