BEGIN TRANSACTION;
CREATE TABLE `warranty` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_text`	TEXT NOT NULL,
	`date`	TEXT NOT NULL
);
CREATE TABLE "type_report" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`template`	INTEGER NOT NULL
);
CREATE TABLE "report" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_type_report`	INTEGER NOT NULL,
	`id_warranty`	INTEGER NOT NULL
);
CREATE TABLE `processes` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_comment`	INTEGER NOT NULL,
	`id_qr_code`	INTEGER NOT NULL,
	`id_user`	INTEGER NOT NULL,
	`id_report`	INTEGER NOT NULL,
	`id_client`	INTEGER NOT NULL
);
CREATE TABLE `jobtitiles` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_role`	INTEGER NOT NULL
);
CREATE TABLE `comment` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`text`	TEXT NOT NULL
);
CREATE TABLE "Users" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_jobtitle`	TEXT NOT NULL,
	`FIO`	TEXT NOT NULL,
	`tel`	TEXT NOT NULL
);
CREATE TABLE `Roles` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Possibilities`	INTEGER NOT NULL
);
CREATE TABLE `QR_codes` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Text`	TEXT NOT NULL,
	`img_link`	TEXT NOT NULL
);
CREATE TABLE `Clients` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`fio`	TEXT NOT NULL,
	`tel`	TEXT NOT NULL
);
COMMIT;
